exp_dir: "experiments/e4e/ffhq_e4e_r50"
output_dir: '../edit_data'
save_code: True

# Data
train_dataset_path: './data/FFHQ'
test_dataset_path: '/home/ssd1/Database/CelebA-HQ/test/182826.jpg'

# Hyper-parameter of training
checkpoint_path: "../pretrained_models/e4e/e4e_ffhq_r50_wp_ori.pt"
stylegan_weights: "../pretrained_models/stylegan2-ffhq-config-f.pt"
batch_size: 8
workers: 8
test_batch_size: 1
test_workers: 1
start_from_latent_avg: True

# Image Loss
lpips_lambda: 0.8
id_lambda: 0.1
l2_lambda: 1.0
w_norm_lambda: 0.
delta_norm_lambda: 2e-4

# Discriminator
w_discriminator_lambda: 0.1
r1: 10
use_w_pool: True

# Progressive Training
progressive_start: 20000
progressive_step_every: 2000

# Wandb
#use_wandb: True
wandb_project: ffhq-inversion