exp_dir: "experiments/psp/ffhq_psp_r50"
output_dir: '../edit_data/psp'
save_code: True
encoder_type: "GradualStyleEncoder"

# Data
train_dataset_path: './data/FFHQ'
test_dataset_path: "/nas/Database/Public/CelebA-HQ/test100"

# Hyper-parameter of training
checkpoint_path: "../pretrained_models/psp/psp_ffhq_r50_wp_ori.pt"
stylegan_weights: "../pretrained_models/stylegan2-ffhq-config-f.pt"
batch_size: 8
workers: 8
test_batch_size: 8
test_workers: 8
start_from_latent_avg: True

# Loss
lpips_lambda: 0.8
id_lambda: 0.1
l2_lambda: 1.0
w_norm_lambda: 0.

# Wandb
#use_wandb: True
wandb_project: ffhq-inversion