exp_dir: "../experiments/edit/e4e_v2"
output_dir: '../edit_data'
save_code: True

# Data
train_dataset_path: '/home/ssd1/Database/FFHQ'
test_dataset_path: '/home/ssd1/Database/CelebA-HQ/train'

# Hyper-parameter of training
checkpoint_path: "../pretrained_models/e4e/e4e_ffhq_r50_wp_ori.pt"
# checkpoint_path: "../experiments/edit/e4e/checkpoints/last.pt"
stylegan_weights: "../pretrained_models/stylegan2-ffhq-config-f.pt"
batch_size: 1
workers: 0
test_batch_size: 1
test_workers: 0
start_from_latent_avg: True

# Image Loss
lpips_lambda: 0.0
id_lambda: 0.0
l2_lambda: 0.0
w_norm_lambda: 0.0
delta_norm_lambda: 0.0
kp_lambda: 1.0

# Optimizer
learning_rate: 0.1

# Discriminator
w_discriminator_lambda: 0.0
r1: 10
use_w_pool: True

# Progressive Training
progressive_start: 20000
progressive_step_every: 2000

# Wandb
#use_wandb: True
wandb_project: ffhq-inversion

# edit
g_layers: 3
extra_weights: True