embed_mode: 'encoder'
test_dataset_path: "../edit_data/restyle/code"
test_info_path: "../edit_data/seg_bisenet_pt"
test_inversion_path: "/nas/Database/Public/CelebA-HQ/test100"
test_batch_size: 1
output_dir: '../test_edit/edit/restyle_id'
save_folder: "edit_optim_seg_l3"
encoder_type: "Encoder4Editing"
checkpoint_path: '../pretrained_models/restyle/restylee4e_ffhq_r50_wp_ori.pt'
start_from_latent_avg: True
optim_step: 1000
optim_l2_lambda: 0.0
optim_lpips_lambda: 0.0
noise_regularize: 0.0
optim_kp_lambda: 0.0
optim_seg_lambda: 1.0
optim_id_lambda: 0.001
optim_w_norm_lambda: 0.0
lr: 0.001
edit_layer: "3"
mode: "seg"