embed_mode: 'encoder'
test_dataset_path: "../edit_data/psp/code"
test_batch_size: 10
output_dir: '../test_edit/edit/psp'
save_folder: "edit_mix_l1"
checkpoint_path: '../pretrained_models/psp/psp_ffhq_r50_wp_ori.pt'
start_from_latent_avg: True
optim_step: 1000
optim_l2_lambda: 0.0
optim_lpips_lambda: 0.0
noise_regularize: 0.0
optim_kp_lambda: 1.0
optim_seg_lambda: 0.0
optim_id_lambda: 0.0
optim_w_norm_lambda: 0.0
lr: 0.001
edit_layer: "1"
mode: "kp"